name: user_app
description: A Flutter article reading application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.2.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0  
  jwt_decoder: ^2.0.1             
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  fluttertoast: ^8.2.4
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true